# Generated by Django 6.0.1 on 2026-05-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_number_plate_vehicle_number_vehicle_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fines',
        ),
    ]
